# Generated by Django 3.1.3 on 2020-12-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('main_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expansion_sets',
            field=models.ManyToManyField(blank=True, to='main.ExpansionSet'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_class',
            field=models.CharField(blank=True, choices=[('demon_hunter', 'Demon Hunter'), ('druid', 'Druid'), ('hunter', 'Hunter'), ('mage', 'Mage'), ('paladin', 'Paladin'), ('priest', 'Priest'), ('rogue', 'Rogue'), ('shaman', 'Shaman'), ('warlock', 'Warlock'), ('warrior', 'Warrior')], max_length=12),
        ),
    ]
