# Generated by Django 3.1.3 on 2020-11-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpansionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('galakrond_awakening', "Galakrond's Awakening"), ('curse_naxxrammas', 'Curse of Naxxramas')], max_length=50)),
                ('card_count', models.PositiveIntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hero_class', models.CharField(choices=[('demon_hunter', 'Demon Hunter'), ('druid', 'Druid'), ('hunter', 'Hunter'), ('mage', 'Mage'), ('paladin', 'Paladin'), ('priest', 'Priest'), ('rogue', 'Rogue'), ('shaman', 'Shaman'), ('warlock', 'Warlock'), ('warrior', 'Warrior'), ('neutral', 'Neutral')], max_length=12)),
                ('mana_cost', models.PositiveIntegerField()),
                ('rarity', models.CharField(choices=[('free', 'Free'), ('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=9)),
                ('image_url', models.URLField()),
                ('expansion_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.expansionset')),
            ],
        ),
    ]
