# Generated by Django 3.1.3 on 2020-11-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('minion', 'Minion'), ('spell', 'Spell'), ('weapon', 'Weapon'), ('hero_card', 'Hero Card')], default='', max_length=9),
            preserve_default=False,
        ),
    ]
