# Generated by Django 3.1.3 on 2020-12-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201201_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='mana_cost',
            field=models.PositiveIntegerField(),
        ),
    ]
