# Generated by Django 3.1.3 on 2020-11-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_collectioncard_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncard',
            name='copies',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
