# Generated by Django 3.1.3 on 2020-11-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_collectioncard_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncard',
            name='copies',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
