# Generated by Django 3.1.3 on 2020-11-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201117_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncard',
            name='copies',
            field=models.PositiveIntegerField(),
        ),
    ]
