# Generated by Django 3.1.3 on 2020-11-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201117_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncard',
            name='copies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
